### ISSUE TITLE
[L5] Support Laravel 5..

### ISSUE THREAD

**Issue by ricardocanelas** [Torann/mediasort#1]
I have this message.. 
**Your requirements could not be resolved to an installable set of packages.**

My composer.json

``` php
    {
        ..
        "require": {
            "laravel/framework": "5.0.*",
            "illuminate/html": "~5.0",
            "torann/mediasort": "0.2.*@dev"
        },
        ..
    }
```
# composer update

```
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - The requested package torann/mediasort could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

```

**Comment by hareluya** [comment]
dear, here's my require blocks hope it can help~

<pre><code>
"require": {
        "laravel/framework": "5.0.*",
        "laravelcollective/html": "~5.0",
        "torann/mediasort": "dev-dev-laravel-5"
    },
</code></pre>

**Comment by ricardocanelas** [comment]
Thank you..now, It's working =)

**Comment by Torann** [comment]
Thanks! I have yet to release the L5 version. So keep in mind it's in beta right now.
