### ISSUE TITLE
something wrong with the meida:fasten

### ISSUE THREAD

**Issue by hareluya** [Torann/mediasort#2]
Dear, thanks for giving the powerful tools.<br>
I encounted something when I use the quickstart.<br>
First,<br><pre><code>

  [ErrorException]  
  mkdir(): No such file or directory
</code></pre>
Then , when I walk round by skip it then I encounted :<br><pre><code>
[Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Str' not found  
</code></pre>
and I then skip again but still encounter :<pre><code>

[InvalidArgumentException]  
  No hint path defined for [mediasort].
</code></pre>
Hope it will help to improve the tools~

**Comment by ricardocanelas** [comment]
- 
  also happens to me

**Comment by Torann** [comment]
Yeah, sorry...I'm having issues with it. The whole cloud based storage is casing some issues with it. I'm working through them though.

**Comment by Torann** [comment]
Just released a fix for this. I always manually add this stuff.
