### ISSUE TITLE
[L5] How dont to replace the existing image

### ISSUE THREAD

**Issue by ricardocanelas** [Torann/mediasort#3]
When I send a new file with the same name ... is overwriting the old image. 
How do I do to create a copy? Example: 'background_2.jpg'

See my configuration:

``` php
        $this->hasMediaFile('image', array(
            'styles' => array(
                'large' => '450x450#',
                'thumb' => '50x50#'
            ),
            'url' => '/files/posts/:id/:basename-:style.:extension',
            'keep_old_files' => true,
            'preserve_files' => true
        ));
```

**Comment by Torann** [comment]
Hmmm... I haven't fully tested all of the `keep_old_files` options. In fact I was debating on removing the option. I couldn't think of a scenario where you would want to keep them. 

May I ask why you wish to keep them? If you upload a new file and keep the old one how are you tracking the old file? It will no longer be saved in the database. This could lead to orphaned files laying everywhere.

**Comment by ricardocanelas** [comment]
Yeah!!.. You're right.  =)
