### ISSUE TITLE
Laravel 5.5 Error with "in_array() expects parameter 2 to be array, null given"

### ISSUE THREAD

**Issue by ablishek** [Torann/mediasort#7]
/vendor/torann/mediasort/src/Manager.php
Line 663

     * @return void
     */
    protected function instanceWrite($property, $value)
    {
        $fieldName = "{$this->name}_{$property}";
 
        if ($property === 'file_name') {
            $this->instance->setAttribute($fieldName, $value);
        }
        else {
            if (in_array($fieldName, $this->instance['fillable'])) {
                $this->instance->setAttribute($fieldName, $value);
            }
        }
    }

$this->instance['fillable'] is not working with Laravel 5.5
But if I change your code to $this->instance->getFillable() then it works properly.

Please see to update this code so we can continue using your package!! # #

**Comment by Torann** [comment]
This was fixed with #9. But it was fixed before then too
